#markdown: rdiscount
#paginate: 8
#paginate_path: "/blog/page:num/"
#excerpt_separator: "<!-- more -->"
paginate: 8
collections:
  posts:
    title: Posts
    paginate_path: "/blog/page/:num/"
plugins:
  - jekyll-paginate
  - jekyll-paginate-multiple

#paginate_path:  "/blog/page:num/"
