#markdown: rdiscount
safe: false
paginate: 8
paginate_path: "/blog/page:num/"
#excerpt_separator: "<!-- more -->"

plugins:
  - jekyll-paginate

#paginate_path:  "/blog/page:num/"

title: Geek41.github.io


