#markdown: rdiscount
#paginate: 8
#paginate_path: "/blog/page:num/"
#excerpt_separator: "<!-- more -->"
lsi: false
 incremental: false
 highlighter: rouge
 kramdown:
   math_engine: mathjax
   syntax_highlighter: rouge
collections:
  posts:
    paginate: 8
    title: Posts
    paginate_path: "/blog/page/:num/"
plugins:
  - jekyll-paginate
  - jekyll-paginate-multiple

#paginate_path:  "/blog/page:num/"
