#markdown: rdiscount
#paginate: 8
#paginate_path: "/blog/page:num/"
#excerpt_separator: "<!-- more -->"
collections:
  posts:
    paginate: 8
    title: Posts
    paginate_path: "/blog/page/:num/"
plugins:
  - jekyll-paginate-multiple

#paginate_path:  "/blog/page:num/"

title: Geek41.github.io


