#markdown: rdiscount
#paginate: 8
#paginate_path: "/blog/page:num/"
#excerpt_separator: "<!-- more -->"
paginate: 8
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-paginate

#paginate_path:  "/blog/page:num/"
