#+STARTUP: hidestars indent
#+OPTIONS: ^:{} toc:t
#+BEGIN_HTML
---
layout: view_toc
comments: true
title: Drolay2.0 需求文档
categories: others
tags: jvm
date: 2000-1-1
keywords: jvm
description: jvm
---

#+END_HTML

#+begin_html
<div id="main">
#+end_html



#+BEGIN_HTML
<!-- more -->
#+END_HTML

* 团队控管

** 发布新团

计划人数，领队人数算在计划人数里。

** TODO 统筹控位?? D:0.5 

因为供应商同时开了几个团，需要根据哪个团的报名情况最好，人工进行票位分配。

供应商对自己持有票数(线下)进行对子团的调控，只有在报名中的团并且为同一天的子团进行票位分配。
票位分配区间，(已报名人数~(计划人数-1))
票位影响报名和出团。

** TODO 批量调价(批量修改) D:1~2

可批量修改子团的计划人数，同行价，市场价，和截止子团。国内的交通方式分为多条来算。

** 定时任务

订单状态为 *确认&款清* 到期做出团设置。出团状态到期做回团处理

** 账期

供应商账期，子团账期。回团以后+账期提交自动结款

** 报名(代理商)


* 产品库
** 创建&编辑新产品
*** 境外
**** 编辑基本信息
产品名称(r),出发城市(单select)-从供应商出发地里面选,目的地(3select)-从供应商目的地里选,类型&主题,途径目的地(列出目的地省份下的所有城市可选可添加).
**** 编辑参考行程
编辑一条旅游线路的行程安排信息.第几天的行程名称,详细内容,酒店星级&名称,早中晚餐.添加目的地图片
**** 编辑可选自费项目
去某个国家或者城市的可选自费项目的增删改查,非必须.
**** 编辑购物信息
去某个国家或者城市的可购物信息的增删改查,非必须.
**** 编辑模板
提供增加和删除内容模板,模板提供给产品的属性:行程特色,费用包含,费用不含,参团须知,备注
*** 国内
**** 交通方式
总:飞机,高铁,动车,卧铺,汽车,轮船,硬座,软座
1) 标准
   旅游的标准交通方式,出团和回团延迟都为0,即出团&回团当天.
2) 非标准
   可添加多条非标准的交通方式,因为有的游客可能做飞机或者做高铁不等.出团&回团delay为,早一天,当天,晚1天,晚2天
**** 参考行程编辑
- 根据产品基本信息中选择的行程天数生成相应天数的行程安排,对其进行编辑.
- 无图片,其他同境外
** 产品复制
复制一条或者多条产品信息,产品编号不能相同,创建时间以复制的时间为准
** 产品删除
将产品状态置为不可用
** 产品查询
可根据产品类型和关键字检索产品
** 出发地
数据来源于地区表,省份表(国家),城市表,为当前供应商常用的旅游线路的出发地.国内外暂定都为国内.
** 目的地
数据来源于地区表,省份表(国家),城市表,为当前供应商常用的旅游线路目的地
*** 国内
添加和删除目的地城市,需要关联显示省份等信息
*** 国外
- 添加和删除国家,统计当前供应商下每个国家的目的地城市数量
- 添加和删除目的地城市,并可以为目的地城市添加图片,在境外编辑产品选择行程的时候会用到.

** 产品类型&主题
对产品主题的增删改查,在编辑产品的时候加载当前用户的主题&类型

* TODO 产品平移

将供应商用户的子团转给其他用户，改变属主

* TODO 轨迹

* 订单控管(c:毛叔)

** 查询订单列表，查看订单，退团，修改订单金额，添加联系人(代理商)，添加游客，添加费用，添加备注，客户查询查看打印

 
** TODO 收支确认单-收款审批 D:0.5

收款审批和确认收款的状态改变，线下流程线上录入。

* 收支项(c:毛叔)
* 代理商管理(c:毛叔)

** TODO 销售专员 delay to doc done




* 直客管理(c:于娜)

* 签证管理(c:张千鸿)

* 业务统计表(to:俊明)

* 财务统计表(to:俊明)

* 统计分析(to:俊明)

** 概况
** 目的地
** 代理商
** 流量统计


* TODO 本部管理(c:建青) 需要维护

** TODO 企业账户 D:0.5~1

添加企业账户的支付信息。
类型 	开户行 	账号 	开户名 	创建日期 	操作

** 组织架构
** 部门管理
** 角色管理
** 账户管理


#+begin_html
</div>
#+end_html
